

from enum import Enum


class TimeSeriesFundamentalType(Enum):
    NUMERIC = "NUMERIC"
    BOOLEAN = "BOOLEAN"
    TEXT = "TEXT"
    TIMESTAMP = "TIMESTAMP"


class TimeSeriesExporter(Enum):
    RAW = "RAW"
    CHANGES_ONLY = "CHANGES_ONLY"
    DISCONTINUITIES_ONLY = "DISCONTINUITIES_ONLY"
    WINDOWED_MEAN = "WINDOWED_MEAN"
    WINDOWED_SUM = "WINDOWED_SUM"
    WINDOWED_COUNT = "WINDOWED_COUNT"
    WINDOWED_BAND = "WINDOWED_BAND"
    AGGREGATE_MEAN = "AGGREGATE_MEAN"
    AGGREGATE_SUM = "AGGREGATE_SUM"
    AGGREGATE_COUNT = "AGGREGATE_COUNT"
    AGGREGATE_BAND = "AGGREGATE_BAND"
